config/routes.rb
TripodMetricsV1::Application.routes.draw do

  resources :dispositivos, only: [:show,:index, :new, :create, :destroy]  do
    resources :rates
  end

  resources :usuarios
  resources :calificador
  resources :static_pages
  resources :logins, only: [:new, :create, :destroy]

  match '/contact2', to: 'calificador#personal'
  match '/payments/payment', :to => 'payments#payment', :as => 'paymentspayment', :via => [:get]
  match '/payments/relay_response', :to => 'payments#relay_response', :as => 'payments_relay_response', :via => [:post]
  match '/payments/receipt', :to => 'payments#receipt', :as => 'payments_receipt', :via => [:get]

  root :to => 'static_pages#home'

  match '/rateservice/:device/:id', to: 'calificador#calificador'
  match '/newrate', to: 'rates#new'
  match '/rate', to: 'rates#index'
  match '/rate/add_entry', to: 'rates#add_entry'

  match '/signin', to: 'logins#new'
  match '/signout', to: 'logins#destroy', via: :delete
  match '/new', to: 'usuarios#new'
  match '/reports', to: 'usuarios#reports'
  match '/report_excel', to: 'usuarios#report_excel'
  match '/index', to: 'usuarios#index'
  match '/contacto', to: 'static_pages#contacto'
  match '/help', to: 'static_pages#help'
  match '/create', to: 'rates#create', via: :get

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    #este codigo se ejecuta cuando se invoca la página home o help o contacto
    $logo="Logo2.png"
  end

  def help
  end

  def contacto
    $logo="Logo2.png"
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/contacto.html.erb
<% provide(:title, 'Contacto')%>
<h1 xmlns="http://www.w3.org/1999/html" xmlns="http://www.w3.org/1999/html" xmlns="http://www.w3.org/1999/html"
    xmlns="http://www.w3.org/1999/html">Contáctanos en:</h1>
<div class="center">
  <a>relacionescomerciales@tripod.net.co</a>
  <br/>057+4+4447962
  <br/> Medellín, Colombia

</div>

app/views/static_pages/help.html.erb
<h1>StaticPages#help</h1>
<p>Find me in app/views/static_pages/help.html.erb</p>

app/views/static_pages/home.html.erb
<% provide(:title, 'Home')%>


<section>
  <section class="pull-right">
    <%= link_to(image_tag('Publ1.png',  size: '400x100'), 'http://www.linkedin.com/groups/For-Better-Service-Community-4609806?gid=4609806&trk=hb_side_g' )%>

  </section>
<div class= "bordered" >
  <div class="span5 " >
  <div class="hero-unit  center"  >
    <!--<h1>Tripod Metrics</h1>   -->
    <h2>

      <b></b>
      <b>¿Es tu primera vez?</b>
      <b></b>
    </h2>
    <%=   link_to "¡Regístrate!", new_path , class: "btn btn-large btn-primary" %>
  </div>

    <div class="hero-unit center" >
      <%= form_for(:login, url: logins_path) do |f| %>

          <%=  f.label :email %>
          <%=  f.text_field :email %>
          <%= f.label :password %>
          <%=  f.password_field :password %>

          <%= f.submit "Ingresar",class: "btn btn-medium btn-success" %>
      <% end %>

    </div>
  </div>

    </div>
 </section>