config/routes.rb
TripodMetricsV1::Application.routes.draw do

  resources :dispositivos, only: [:show,:index, :new, :create, :destroy]  do
    resources :rates
  end

  resources :usuarios
  resources :calificador
  resources :static_pages
  resources :logins, only: [:new, :create, :destroy]

  match '/contact2', to: 'calificador#personal'
  match '/payments/payment', :to => 'payments#payment', :as => 'paymentspayment', :via => [:get]
  match '/payments/relay_response', :to => 'payments#relay_response', :as => 'payments_relay_response', :via => [:post]
  match '/payments/receipt', :to => 'payments#receipt', :as => 'payments_receipt', :via => [:get]

  root :to => 'static_pages#home'

  match '/rateservice/:device/:id', to: 'calificador#calificador'
  match '/newrate', to: 'rates#new'
  match '/rate', to: 'rates#index'
  match '/rate/add_entry', to: 'rates#add_entry'

  match '/signin', to: 'logins#new'
  match '/signout', to: 'logins#destroy', via: :delete
  match '/new', to: 'usuarios#new'
  match '/reports', to: 'usuarios#reports'
  match '/report_excel', to: 'usuarios#report_excel'
  match '/index', to: 'usuarios#index'
  match '/contacto', to: 'static_pages#contacto'
  match '/help', to: 'static_pages#help'
  match '/create', to: 'rates#create', via: :get

end

app/models/rate.rb
class Rate < ActiveRecord::Base

  attr_accessible :id, :device_id, :in_date, :selected_option, :valor, :mes, :ano, :dia, :hora, :mesint
  validates :device_id, presence:true


  belongs_to :dispositivo
  belongs_to :usuario,    :foreign_key => "device_id"

  #rate.dispositivo - entrega el objeto Usuario asociado a ese rate
  #dispositivo.rates - entrega un array de todos los rates de ese dispositivo
  #dispositivo.rates.create(arg) crea un rate con el respectivo device_id=dispositivo.id
  #dispositivo.rates.create!(arg) crea un rate exception failure
  #dispositivo.rates.build(arg) retorna un nuevo objeto rates (device_id=dispositivo.id)


 end

app/controllers/rates_controller.rb
class RatesController < ApplicationController
  before_filter :signed_in_user, only: [:edit, :show]
  before_filter :admin_user, only: [:destroy, :index]
  # GET /rates
  # GET /rates.json
  def index
    @rates = Rate.all

    #@rate = Rate.all
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @rates }
    end


  end

  # GET /rates/1
  # GET /rates/1.json
  def show

    @rate = Rate.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @rate }
    end
  end

  # GET /rates/new
  # GET /rates/new.json
  def new
    @rate = Rate.new
    #respond_to do |format|
     #format.html # new.html.erb
     #format.json { render json: @rate }
    #end
  end

  # GET /rates/1/edit
  def edit
    #@rate = Rate.find(params[:id])
  end

  # POST /rates
  # POST /rates.json

  def create
    if params[:rate][:selected_option] == "E"
      params[:rate][:valor] = 5
    end
    if params[:rate][:selected_option] == "B"
      params[:rate][:valor] = 4
    end
    if params[:rate][:selected_option] == "R"
      params[:rate][:valor] = 3
    end
    if params[:rate][:selected_option] == "M"
      params[:rate][:valor] = 2
      @userid=Dispositivo.find_by_device_id(params[:rate][:device_id]).usuario_id
      @user = Usuario.find(@userid)
      @device= params[:rate][:device_id]
      UserMailer.welcome_email(@user).deliver
    end
    #time=Time.new
    time = Time.parse(params[:rate][:in_date])
    params[:rate][:mesint] = time.strftime("%m")
    params[:rate][:ano] = time.strftime("%Y")
    params[:rate][:dia] = time.strftime("%d")
    params[:rate][:hora] = time.strftime("%H")

    params[:rate][:in_date] = params[:rate][:in_date]
    #params[:rate][:ano] = 2012
    #params[:rate][:dia] = "15"
    #params[:rate][:hora] = 12

    @rate = Rate.new(params[:rate])

    respond_to do |format|

    if @rate.save
      #format.html { redirect_to @rate, notice: 'Usuario was successfully created.' }
      #format.json { render json: @rate, status: :created, location: @rate }
      #render :xml => "<success/>"

    else
        #format.html { render action: "new" }
        #format.json { render json: @rate.errors, status: :unprocessable_entity }
    end

    end

  end


  # PUT /rates/1
  # PUT /rates/1.json
  def update
    @rate = Rate.find(params[:id])

    respond_to do |format|
      if @rate.update_attributes(params[:rate])
        format.html { redirect_to @rate, notice: 'Rate was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @rate.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rates/1
  # DELETE /rates/1.json
  def destroy
    @rate = Rate.find(params[:id])
    @rate.destroy

    respond_to do |format|
      format.html { redirect_to rates_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/rates_helper.rb
module RatesHelper

end

app/views/rates/_form.html.erb
<%= form_for(@rate) do |f| %>
  <% if @rate.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@rate.errors.count, "error") %> prohibited this rate from being saved:</h2>

      <ul>
      <% @rate.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :device_id %><br />
    <%= f.text_field :device_id %>
  </div>
  <div class="field">
    <%= f.label :in_date %><br />
    <%= f.datetime_select :in_date %>
  </div>
  <div class="field">
    <%= f.label :selected_option %><br />
    <%= f.text_field :selected_option %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/rates/_rate.html.erb
<li class="center">

</li>

app/views/rates/add_entry.html.erb
<title>OK</title>

app/views/rates/edit.html.erb
<h1>Editing rate</h1>

<%= render 'form' %>

<%= link_to 'Show', @rate %> |
<%= link_to 'Back', rates_path %>

app/views/rates/index.html.erb
<h1>Calificaciones </h1>

<table class="center table table-striped ">
  <tr>
    <th>Dispositivo</th>
    <th>Fecha</th>
    <th>Opción seleccionada</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @rates.each do |rate| %>
  <tr>
    <td><%= rate.device_id %></td>
    <td><%= rate.created_at %></td>
    <td><%= rate.in_date %></td>
    <td><%= rate.selected_option %></td>
    <td><%= link_to 'Mostrar', rate %></td>
    <td><%= link_to 'Eliminiar', rate, method: :delete, data: { confirm: 'Está seguro de eliminar?' } %></td>
  </tr>
<% end %>
</table>

<br />
<!--        para que no se puedan agregarcalificacioens au´n siendo administrador

-->

app/views/rates/new.html.erb
<h1>New rate</h1>

<%= render 'form' %>

<%= link_to 'Back', rates_path %>

app/views/rates/show.html.erb
<p id="notice"><%= notice %></p>


<p>
  <b>Dispositivo</b>
  <%= @rate.device_id %>
</p>

<p>
  <b>Fecha de creación:</b>
  <%= @rate.in_date %>
</p>

<p>
  <b>Calificación:</b>
  <%= @rate.selected_option %>
</p>


<%= link_to 'Edit', edit_rate_path(@rate) %> |
<%= link_to 'Back', rates_path %>