config/routes.rb
TripodMetricsV1::Application.routes.draw do

  resources :dispositivos, only: [:show,:index, :new, :create, :destroy]  do
    resources :rates
  end

  resources :usuarios
  resources :calificador
  resources :static_pages
  resources :logins, only: [:new, :create, :destroy]

  match '/contact2', to: 'calificador#personal'
  match '/payments/payment', :to => 'payments#payment', :as => 'paymentspayment', :via => [:get]
  match '/payments/relay_response', :to => 'payments#relay_response', :as => 'payments_relay_response', :via => [:post]
  match '/payments/receipt', :to => 'payments#receipt', :as => 'payments_receipt', :via => [:get]

  root :to => 'static_pages#home'

  match '/rateservice/:device/:id', to: 'calificador#calificador'
  match '/newrate', to: 'rates#new'
  match '/rate', to: 'rates#index'
  match '/rate/add_entry', to: 'rates#add_entry'

  match '/signin', to: 'logins#new'
  match '/signout', to: 'logins#destroy', via: :delete
  match '/new', to: 'usuarios#new'
  match '/reports', to: 'usuarios#reports'
  match '/report_excel', to: 'usuarios#report_excel'
  match '/index', to: 'usuarios#index'
  match '/contacto', to: 'static_pages#contacto'
  match '/help', to: 'static_pages#help'
  match '/create', to: 'rates#create', via: :get

end

app/models/dispositivo.rb
class Dispositivo < ActiveRecord::Base
  attr_accessible :creado_por, :device_id, :sede_id, :status, :usuario_id, :device_type
  #quitamos usuario id de los atributos accesibles para evitar edición
  belongs_to :usuario     #así creo la asociación entre tablas
                          #quiere decir que micropost tiene un usuario asociado
                          #has many es que un usuario tiene mucho devices

  has_many :rates

  #validates :device_id, presence: true, length: { maximum: 6 }

  default_scope order: 'dispositivos.created_at DESC' #esto es SQL por orden descendiente

end

app/controllers/dispositivos_controller.rb
class DispositivosController < ApplicationController
  before_filter :signed_in_user, only: [:edit, :create, :destroy, :show]
  before_filter :admin_user, only: [:edit,:index, :destroy]
  #chequeamos que esé logiado
  #está en logins Helper



  # GET /dispositivos
  # GET /dispositivos.json
  def index
    @dispositivos = Dispositivo.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @dispositivos }
    end
  end

  # GET /dispositivos/1
  # GET /dispositivos/1.json
  def show

    @dispositivo = Dispositivo.find(params[:id])
    @dispositivo_id = @dispositivo.device_id
    @califica = Rate.find_all_by_device_id(@dispositivo_id)
    #@cali = @califica.find(params[selected_option: "E"])


    respond_to do |format|
      format.html #show.html.erb
      #format.html usuario_path
      format.json { render json: @dispositivo }
    end
  end

  # GET /dispositivos/new
  # GET /dispositivos/new.json
  def new
    @dispositivo = Dispositivo.new

    chars = 'ABCDEFGHJKLMNOPQRSTUVWXYZ'
    number='0123456789'
    @codigodevice = ''
    3.times { |i| @codigodevice << chars[rand(7)] }
    3.times { |i| @codigodevice << number[rand(7)] }
    @codigodevice

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @dispositivo }
    end
  end

  # GET /dispositivos/1/edit
  def edit
    @dispositivo = Dispositivo.find(params[:id])
    respond_to do |format|
      format.html # edit.html.erb
      format.json { render json: @dispositivos }
    end
  end

  # POST /dispositivos
  # POST /dispositivos.json
  def create
   @dispositivo = Dispositivo.new(params[:dispositivo])
    @dispositivo = current_user.dispositivos.build(params[:dispositivo])
    #@dispositivo = current_usuario.dispositivos.build(params[:dispositivo])
    respond_to do |format|
      if @dispositivo.save
        format.html { redirect_to @dispositivo, notice: 'Dispositivo was successfully created.' }
        #format.json { render json: , status: :created, location: @usuario }
      else
        format.html { render action: "new" }
        format.json { render json: @dispositivo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /dispositivos/1
  # PUT /dispositivos/1.json
  def update
    @dispositivo = Dispositivo.find(params[:id])

    respond_to do |format|
      if @dispositivo.update_attributes(params[:dispositivo])
        format.html { redirect_to @dispositivo, notice: 'Dispositivo was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @dispositivo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dispositivos/1
  # DELETE /dispositivos/1.json
  def destroy
    @dispositivo = Dispositivo.find(params[:id])
    @dispositivo.destroy

    respond_to do |format|
      format.html { redirect_to dispositivos_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/dispositivos_helper.rb
module DispositivosHelper

  def current_device
    @current_device = Dispositivo.find(params[:id])
  end


end

app/views/dispositivos/_dispositivo.html.erb
<li class="center">
  <span class="content " ><%= link_to dispositivo.device_id, dispositivo%>

    <% if dispositivo.device_type=="Web"%>
          <i class="icon-globe"></i>
    <% end %>
    <% if dispositivo.device_type=="Consola"%>
          <i class="icon-tasks"></i>
    <% end %>
         <%=
        if dispositivo.status?
          "Activo "
        elsif
        "Inactivo"
        end

    %> </span>
  <span class="timestamp ">
    Creado <%= time_ago_in_words(dispositivo.created_at) %>
  </span>

</li>

app/views/dispositivos/_form.html.erb
<%= form_for(@dispositivo) do |f| %>
  <% if @dispositivo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@dispositivo.errors.count, "error") %> prohibited this dispositivo from being saved:</h2>

      <ul>
      <% @dispositivo.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>


   <div class="checkbox">

     Status <%= f.check_box :status %>
     <br />
     <br />
   </div>
  <!--
  <div class="input-small">

    ID Usuario<%= f.number_field :usuario_id %>
    <br />
    <br />
  </div>
  -->
  <div class="input-medium">
     Creado por <%= f.text_field :creado_por %>
    <br />
    <br />
  </div>
  <div class="input-medium">
   <!-- <%= f.label "Código Dispositivo" %>   -->
    Código Dispositivo <%= f.text_field :device_id,:value => @codigodevice %>

    <br />
    <br />
  </div>

    <div class="input-medium">
      Tipo Dispositivo
      <%= f.select(:device_type, options_for_select(["Web", "Consola"])) %>
    </div>


  <div class="input-small">
  Sede<%= f.number_field :sede_id %>
  </div>
   <br />
   <br />

 <%= f.submit "Crear", class:" btn-medium btn-primary" %>



<% end %>
<!--<form action="https://www.paypal.com/cgi-bin/webscr" method="post">
  <input type="hidden" name="cmd" value="_s-xclick">
  <input type="hidden" name="hosted_button_id" value="MD259QRXXXDF6">
  <input type="image" src="https://www.paypalobjects.com/en_US/i/btn/btn_subscribeCC_LG.gif" border="0" name="submit" alt="PayPal - The safer, easier way to pay online!">
  <img alt="" border="0" src="https://www.paypalobjects.com/es_XC/i/scr/pixel.gif" width="1" height="1">
</form>  -->

app/views/dispositivos/edit.html.erb
<h1>Editing dispositivo</h1>

<%= render 'form' %>

<%= link_to 'Mostrar', @dispositivo %> |
<%= link_to 'Regresar', dispositivos_path %>

app/views/dispositivos/index.html.erb
<h1>Dispositivos</h1>

<table  class="table .table-condensed ">
  <tr>
    <th>Usuario</th>
    <th>Creado por</th>
    <th>Status</th>
    <th>Device</th>
    <th>Sede</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @dispositivos.each do |dispositivo| %>
  <tr>
    <td><%= dispositivo.usuario_id %></td>
    <td><%= dispositivo.creado_por %></td>
    <td><%= dispositivo.status %></td>
    <td><%= link_to dispositivo.device_id, dispositivo %></td>
    <td><%= dispositivo.sede_id %></td>
    <td><%= link_to 'Mostar', dispositivo %></td>
    <td><%= link_to 'Editar' %></td>
    <td><%= link_to 'Borrar', dispositivo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Dispositivo', new_dispositivo_path %>

app/views/dispositivos/new.html.erb
<% provide(:title, 'Registro')%>
<h1>Nuevo Dispositivo</h1>

  <%= render 'form' %>


<%= link_to 'Regresar', dispositivos_path %>

app/views/dispositivos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Usuario:</b>
  <%= @dispositivo.usuario_id %>
</p>

<p>
  <b>Creado por:</b>
  <%= @dispositivo.creado_por %>
</p>

<p>
  <b>Status:</b>
  <%= @dispositivo.status %>
</p>

<p>
  <b>Device:</b>
  <%= @dispositivo.device_id %>
</p>

<p>
  <b>Tipo:</b>
  <%= @dispositivo.device_type %>
  <% if @dispositivo.device_type=="Web"%>
      <i class="icon-globe"></i>
  <% end %>
  <% if @dispositivo.device_type=="Consola"%>
      <i class="icon-tasks"></i>
  <% end %>
</p>

<p>
  <b>Sede:</b>
  <%= @dispositivo.sede_id %>
</p>

<h2 class="center">Calificaciones </h2>

<table  class="table .table-condensed ">
  <% @califica.each do |calificacion| %>
      <tr>
        <td><%= calificacion.selected_option  %></td>
        <td><span class="timestamp "> <%= calificacion.created_at %> </span></td>
        <td><%= calificacion.mesint %></td>
      </tr>
  <% end %>



</table>

<% if current_usuario.admin? %>
    <%= link_to 'Dispositivos', dispositivos_path %>|
<% else %>
    <%= link_to 'Perfil', current_user %>|
<% end %>